### ISSUE TITLE
前端设计风格问题

### ISSUE THREAD

**Issue by Shi-k22-tsinghua** [shoedogodo/Daily-Running-Assistant#10]
前端设计页面格式时，我们是设计暗色调呢？还是亮色调呢？还是既设计一个白天模式又设计一个夜间模式呢？

参考下面的几张图片：

![图片](https://github.com/user-attachments/assets/b1d120a8-029a-4a54-af92-fb3dc165d96c)

![图片](https://github.com/user-attachments/assets/f24430d4-ad97-4237-9e47-693a296f5f9e)

**Comment by cuber17** [comment]
暗色调看起来好看些，但是用户大部分使用肯定是在白天，暗色点似乎又有点不实用

**Comment by Shi-k22-tsinghua** [comment]
那么我们在当前阶段可以先按照亮色调来编程，后面考虑是否设置白天模式和夜间模式的调节
